### ISSUE TITLE
add cuml solver

### ISSUE THREAD

**Issue by agramfort** [benchopt/benchmark_logreg_l2#23]
https://docs.rapids.ai/api/cuml/stable/api.html#cuml.LogisticRegression

**Comment by tanglef** [comment]
So, I've got the code for this.
The thing is, the CI will never be ok, because `cuml` only supports GPU computing, and github CI machines do not provide a GPU. 
 Maybe we could talk sometime about running the CI of such solvers on a machine with one (as using a GPU is quite common now) . WDYT @tomMoral ?

**Comment by agramfort** [comment]
@tanglef do you have good results with cuml?

**Comment by tanglef** [comment]
@tomMoral I have modified the `skip` for now then, and when I'll have some more time I will look into GPUci, thanks

@agramfort Yes, especially when there is a lot of data (quite obviously...) When the data is small, technically there is no need to use a GPU (the overhead will be too big compared to the final gain)

![Capture d’écran de 2022-03-31 10-23-16](https://user-images.githubusercontent.com/57089823/161011583-4ab94446-8241-4997-aa69-a94c2f0b7f19.png)

**Comment by agramfort** [comment]
nice !

just put in the skip function something that detects if GPU is available and if not skip the solver?

**Comment by tanglef** [comment]
Yes, I have used the `_get_cuda_version` function that was created for the `sysinfo`. If it is `None` then we skip the test for now.
And tests are always skipped under MacOs as it is not supported at all :)
